name: Build and publish to AWS
on:
    push:
        branches:
            - mainline
            - GithubActionsFinangling
jobs:
    run:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
            - uses: taiki-e/install-action@v2
              with:
                tool: zola@0.19.1
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: us-east-1
                role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
                role-session-name: GitHubActions
            - name: Build Zola site
              run: |
                cd zola
                zola build
            - name: Deploy Zola site
              run: |
                cd cdk
                npm run cdk deploy
